### ISSUE TITLE
TypeError in external-sources.ts

### ISSUE THREAD

**Issue by thkruz** [thkruz/keeptrack.space#593]
#### User Description
Type what you were trying to do here...

#### Error Title
TypeError
#### Error Message
Cannot read properties of undefined (reading 'split')
#### Stack
TypeError: Cannot read properties of undefined (reading 'split')
    at Pn (http://www.keeptrack.space/js/main.63fa6755769926409a9c.js:648:1057)
    at Mn.i.onload (http://www.keeptrack.space/js/main.63fa6755769926409a9c.js:648:906)

**Comment by thkruz** [comment]
This is superseded by #676
