### ISSUE TITLE
Error in Global Error Trapper

### ISSUE THREAD

**Issue by thkruz** [thkruz/keeptrack.space#594]
#### User Description
Type what you were trying to do here...

#### Error Title
Error
#### Error Message
N2YO TLE 1 is not a valid TLE -- Yo
#### Stack
Error: N2YO TLE 1 is not a valid TLE -- Yo
    at Gn (http://www.keeptrack.space/js/main.63fa6755769926409a9c.js:648:1886)
    at On.i.onload (http://www.keeptrack.space/js/main.63fa6755769926409a9c.js:648:2412)

**Comment by thkruz** [comment]
I am going to disable the external sources plugin for now and move this task to the next release. I want to rewrite this to be website agnostic. Just a big text box where you can copy and paste a TLE from any source you have.
