### ISSUE TITLE
TypeError in updateSatInfo

### ISSUE THREAD

**Issue by thkruz** [thkruz/keeptrack.space#607]
#### User Description
Tried loading the page "https://www.keeptrack.space/?sat=80728&rate=0&date=1667497138552"

#### Error Title
TypeError
#### Error Message
Cannot set properties of null (setting 'innerHTML')
#### Stack
TypeError: Cannot set properties of null (setting 'innerHTML')
    at i (https://www.keeptrack.space/js/main.81153b03833035b2f771.js:2682:1901)
    at i.next (<anonymous>)
    at https://www.keeptrack.space/js/main.81153b03833035b2f771.js:2682:6573
    at new Promise (<anonymous>)
    at Object.sae [as cb] (https://www.keeptrack.space/js/main.81153b03833035b2f771.js:2682:6309)
    at https://www.keeptrack.space/js/main.81153b03833035b2f771.js:2:2147989
    at Array.forEach (<anonymous>)
    at Object.updateSelectBox (https://www.keeptrack.space/js/main.81153b03833035b2f771.js:2:2147975)
    at Object.Ce [as cb] (https://www.keeptrack.space/js/main.81153b03833035b2f771.js:3057:16224)
    at https://www.keeptrack.space/js/main.81153b03833035b2f771.js:2:2149764

**Comment by thkruz** [comment]
`updateSelectBoxCoreCallback` is running before ui is fully initialized. Defensive code added.
