### ISSUE TITLE
TypeError in external-sources.ts - N2YO

### ISSUE THREAD

**Issue by thkruz** [thkruz/keeptrack.space#612]
#### User Description
Type what you were trying to do here...

#### Error Title
TypeError
#### Error Message
Cannot read properties of undefined (reading 'split')
#### Stack
TypeError: Cannot read properties of undefined (reading 'split')
    at En (http://www.keeptrack.space/js/main.9f40782ae0d8066bef07.js:648:1057)
    at On.i.onload (http://www.keeptrack.space/js/main.9f40782ae0d8066bef07.js:648:906)

**Comment by thkruz** [comment]
This is superseded by #676
