### ISSUE TITLE
Error in Global Error Trapper - Celestrak

### ISSUE THREAD

**Issue by thkruz** [thkruz/keeptrack.space#613]
#### User Description
Type what you were trying to do here...

#### Error Title
Error
#### Error Message
N2YO TLE 1 is not a valid TLE -- Yo
#### Stack
Error: N2YO TLE 1 is not a valid TLE -- Yo
    at Rn (http://www.keeptrack.space/js/main.9f40782ae0d8066bef07.js:648:1886)
    at Nn.i.onload (http://www.keeptrack.space/js/main.9f40782ae0d8066bef07.js:648:2412)

**Comment by thkruz** [comment]
This is superseded by #676
