### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by robertariast** [thkruz/keeptrack.space#635]
#### User Description
Type what you were trying to do here...

#### Error Title
TypeError
#### Error Message
Cannot read properties of undefined (reading 'substring')
#### Stack
TypeError: Cannot read properties of undefined (reading 'substring')
    at e.createSatrec (https://www.keeptrack.space/js/main.86175ce9ac90d8708b40.js:2:2000930)
    at Object.altitudeCheck (https://www.keeptrack.space/js/main.86175ce9ac90d8708b40.js:2995:62490)
    at Ra.Na.satData.<computed>.getAltitude.Na.satData.<computed>.getAltitude (https://www.keeptrack.space/js/main.86175ce9ac90d8708b40.js:3332:334258)
    at Object.update (https://www.keeptrack.space/js/main.86175ce9ac90d8708b40.js:27:25968)
    at Object.updateLoop (https://www.keeptrack.space/js/main.86175ce9ac90d8708b40.js:3332:306322)
    at Wn (https://www.keeptrack.space/js/main.86175ce9ac90d8708b40.js:3332:300760)

**Comment by thkruz** [comment]
Error is in the getAlt routine of satMath. It appears you selected an object which had an invalid TLE (missile maybe?) and rather than just giving you an error on the screen it threw a hard fault. 

I added an error for the console and a default value to return instead of crashing.

If there is anything you can provide about what you were doing that would help, but this will work for now. I'll push the update tonight.
