### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by zestones** [thkruz/keeptrack.space#664]
#### User Description
Type what you were trying to do here...

#### Error Title
TypeError
#### Error Message
Cannot read properties of null (reading 'TLE1')
#### Stack
TypeError: Cannot read properties of null (reading 'TLE1')
    at Object.getOrbitByLatLon (http://www.keeptrack.space/js/main.387d2ec0f438ffe26383.js:3000:74487)
    at Fi (http://www.keeptrack.space/js/main.387d2ec0f438ffe26383.js:1256:891)
    at HTMLFormElement.<anonymous> (http://www.keeptrack.space/js/main.387d2ec0f438ffe26383.js:1341:80)

**Comment by thkruz** [comment]
Catalog appears to have a hidden \r character. Working on it now.

**Comment by thkruz** [comment]
Added code to the catalog manager to strip out the /r's - should be good to go now.
