### ISSUE TITLE
Error in Global Error Trapper

### ISSUE THREAD

**Issue by thkruz** [thkruz/keeptrack.space#665]
#### User Description
Catalog appears to have a hidden \r character.

#### Error Title
Error
#### Error Message
Invalid TLE1: length is not 69 - 1 18361U 87080A   23090.83797968 +.00000162 +00000+0 +25439-3 0 09997
#### Stack
Error: Invalid TLE1: length is not 69 - 1 18361U 87080A   23090.83797968 +.00000162 +00000+0 +25439-3 0 09997
    at Object.insertNewAnalystSatellite (https://www.keeptrack.space/js/main.387d2ec0f438ffe26383.js:3337:339790)
    at HTMLDivElement.go (https://www.keeptrack.space/js/main.387d2ec0f438ffe26383.js:1370:711)

**Comment by thkruz** [comment]
Duplicate of #664
