### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by masters1212** [thkruz/keeptrack.space#754]
#### User Description
Type what you were trying to do here...

#### Error Title
TypeError
#### Error Message
Cannot read properties of undefined (reading 'xke')
#### Stack
TypeError: Cannot read properties of undefined (reading 'xke')
    at e.propagate (https://www.keeptrack.space/app/js/main.2989272364f8bde62ae3.js:2:1709113)
    at m.getRae (https://www.keeptrack.space/app/js/main.2989272364f8bde62ae3.js:931:9428)
    at d.getTearData (https://www.keeptrack.space/app/js/main.2989272364f8bde62ae3.js:931:10854)
    at Object.cb (https://www.keeptrack.space/app/js/main.2989272364f8bde62ae3.js:596:2216)
    at https://www.keeptrack.space/app/js/main.2989272364f8bde62ae3.js:2:1797302
    at Array.forEach (<anonymous>)
    at Object.updateSelectBox (https://www.keeptrack.space/app/js/main.2989272364f8bde62ae3.js:2:1797288)
    at W.updateSelectBox (https://www.keeptrack.space/app/js/main.2989272364f8bde62ae3.js:931:1154160)
    at Re.gameLoop (https://www.keeptrack.space/app/js/main.2989272364f8bde62ae3.js:1337:15231)

**Comment by thkruz** [comment]
Bug in trying to get range az el data on missiles.

**Comment by thkruz** [comment]
Fixed in #755
