### ISSUE TITLE
Opening in cellphone chrome Error in Global Error Trapper

### ISSUE THREAD

**Issue by marirene12** [thkruz/keeptrack.space#789]
#### User Description
Type what you were trying to do here...

#### Error Title
Error
#### Error Message
Vertex shader compilation failed: 
#### Stack
Error: Vertex shader compilation failed: 
    at i.createVertexShader (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:708:97363)
    at i.createProgramFromCode (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:708:93502)
    at Se.initGodraysProgram_ (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1340:2420)
    at Se.initGodrays (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1340:1750)
    at Ae.resizePostProcessingTexture (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1340:18024)
    at Ae.drawOptionalScenery (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1340:9450)
    at Ae.draw (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1340:9083)
    at Ye.draw_ (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1444:2984)
    at Ye.gameLoop (https://www.keeptrack.space/app/js/main.bf8218c52edfa9a994cc.js:1391:15812)

**Comment by thkruz** [comment]
Can you provide any information about what type of phone you are using?

I suspect there is an issue with WebGL 2.0 since the godrays shader is the only one that draws to anything other than the canvas. The other thing to try is running:

https://www.keeptrack.space/app/?preset=ops-center

This mode disable the sun (and godrays). That would provide more clear evidence the issue is with the sun. Long term I'd love to have something that detects this issue and auto-disables the sun, but in the short term I could add a flag you can set to only skip the sun and leave everything else as default.

**Comment by thkruz** [comment]
I was able to recreate it on accident on my desktop computer, but am having trouble getting it to repeat itself reliably. It appears to be some kind of race condition. So far I have only gotten it when loading an external TLE - I suspect it is launching some code before the TLEs are finished downloading.

**Comment by thkruz** [comment]
I believe this has been fixed by the new catalog loader code. External catalogs are now handled in a different manner that should make it a non-issue. I am closing it as fixed.
