### ISSUE TITLE
Lost WebGl Context - "Cannot read canvas on undefined"

### ISSUE THREAD

**Issue by Geovanny2023** [thkruz/keeptrack.space#832]
#### User Description
Type what you were trying to do here...

#### Error Title
TypeError
#### Error Message
Cannot read properties of undefined (reading 'canvas')
#### Stack
TypeError: Cannot read properties of undefined (reading 'canvas')
    at lt.resizeCanvas (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1512:111124)
    at https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1512:105737

**Comment by thkruz** [comment]
Looks like you lost the canvas during a screen resize. Added a fix that will reinitialize webgl if that happens. Can you provide any information about your setup? 

Desktop or mobile?
What browser?
