### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by reps8** [thkruz/keeptrack.space#833]
#### User Description
Type what you were trying to do here...

#### Error Title
TypeError
#### Error Message
Cannot create property 'x' on number '0'
#### Stack
TypeError: Cannot create property 'x' on number '0'
    at ae.updatePosVel (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1039:1232700)
    at $.getSat (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1039:1187509)
    at Te.updateOrbitBuffer (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1090:10493)
    at Object.Z [as cb] (https://www.keeptrack.space/app/js/590.bd7312813e75d6e19dda.js:214:166)
    at https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:2:2060534
    at Array.forEach (<anonymous>)
    at Object.updateLoop (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:2:2060520)
    at lt.update (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1512:114366)
    at ct.update_ (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1565:5625)
    at ct.gameLoop (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1512:117356)

**Comment by thkruz** [comment]
Closing this as a duplicate to #834
