### ISSUE TITLE
n0

### ISSUE THREAD

**Issue by reps8** [thkruz/keeptrack.space#834]
#### User Description
Type what you were trying to do here...

#### Error Title
TypeError
#### Error Message
Cannot create property 'x' on number '0'
#### Stack
TypeError: Cannot create property 'x' on number '0'
    at ae.updatePosVel (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1039:1232700)
    at $.getSat (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1039:1187509)
    at Te.updateOrbitBuffer (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1090:10493)
    at Object.Z [as cb] (https://www.keeptrack.space/app/js/590.bd7312813e75d6e19dda.js:214:166)
    at https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:2:2060534
    at Array.forEach (<anonymous>)
    at Object.updateLoop (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:2:2060520)
    at lt.update (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1512:114366)
    at ct.update_ (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1565:5625)
    at ct.gameLoop (https://www.keeptrack.space/app/js/main.41a3572822fe0794e242.js:1512:117356)

**Comment by thkruz** [comment]
I added a check for this situation in 30ccd82. Can you explain more details about what you were doing when this happened? It seems like you were either hovering over a dot or recently selected one. I'd ideally like to fix the cause of this error vs just catching it when it happens.

**Comment by thkruz** [comment]
There is currently a reset happening at the beginning of this method to ensure velocity was not incorrectly set to 0. Yet I am still getting bug reports saying velocity was set to 0 later on when an attempt was made to set the x value. I am going to update the bug reporter to include details about the version of KeepTrack that is running. It is possible that older versions are being used somewhere.

**Comment by thkruz** [comment]
Premade missile simulations might have been the culprit. I fixed that scenario, but will leave the velocity check in place until I rule out other scenarios.

**Comment by thkruz** [comment]
Replaced the silent defensive reset in updatePosVel with an instrumented invariant helper, and applied the same guard to the only other unguarded velocity.x = write site found in the codebase.
