### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by adminadmin12345678** [thkruz/keeptrack.space#880]
#### User Description
Type what you were trying to do here...

#### Error Title
TypeError
#### Error Message
Cannot read properties of undefined (reading 'bindBuffer')
#### Stack
TypeError: Cannot read properties of undefined (reading 'bindBuffer')
    at de.updateFirstPointOut (file:///D:/keeptrack.space-gh-pages1/keeptrack.space-gh-pages/js/main.ca33b429606701f026a9.js:989:13642)
    at et.updatePrimarySatellite_ (file:///D:/keeptrack.space-gh-pages1/keeptrack.space-gh-pages/js/main.ca33b429606701f026a9.js:1411:113256)
    at et.update (file:///D:/keeptrack.space-gh-pages1/keeptrack.space-gh-pages/js/main.ca33b429606701f026a9.js:1411:113974)
    at it.update_ (file:///D:/keeptrack.space-gh-pages1/keeptrack.space-gh-pages/js/main.ca33b429606701f026a9.js:1452:5558)
    at it.gameLoop (file:///D:/keeptrack.space-gh-pages1/keeptrack.space-gh-pages/js/main.ca33b429606701f026a9.js:1411:117272)

**Comment by thkruz** [comment]
From what I can see you were running this from a Windows desktop without an http server. Your error occurred while drawing the orbit lines because of an issue finding the WebGl Context. I need more information about what browser and version of Windows you were running. Also can you please describe what you saw - did it fail immediately on page load or did it happen later when you were doing something?

**Comment by thkruz** [comment]
Never got any information to help solve this. Since it seems like a local issue, I am closing it.
