### ISSUE TITLE
Error in Global Error Trapper

### ISSUE THREAD

**Issue by LevdavidovichB** [thkruz/keeptrack.space#885]
#### User Description
Type what you were trying to do here...

#### Error Title
Error
#### Error Message
Sensor not found
#### Stack
Error: Sensor not found
    at v.calculateSensorPos (https://www.keeptrack.space/app/js/main.dcff11629d94a140c915.js:478:23904)
    at et.orbitsAbove (https://www.keeptrack.space/app/js/main.dcff11629d94a140c915.js:1411:107173)
    at et.update (https://www.keeptrack.space/app/js/main.dcff11629d94a140c915.js:1411:114166)
    at it.update_ (https://www.keeptrack.space/app/js/main.dcff11629d94a140c915.js:1452:5558)
    at it.gameLoop (https://www.keeptrack.space/app/js/main.dcff11629d94a140c915.js:1411:117272)

**Comment by thkruz** [comment]
I was able to replicate by selecting a sensor, selecting planetarium view, then resetting the sensor.

**Comment by thkruz** [comment]
Fixed in 69fd711. Will be live with the next update.
