### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by lusito403** [thkruz/keeptrack.space#902]
#### User Description
Type what you were trying to do here...

#### Version
9.0.3 - June 25, 2024
#### Error Title
TypeError
#### Error Message
Cannot read properties of null (reading 'sccNum')
#### Stack
TypeError: Cannot read properties of null (reading 'sccNum')
    at F.nearObjectsLinkClick_ (https://www.keeptrack.space/app/js/main.d2d0055a530f0fc4e587.js:64:32787)
    at HTMLDivElement.<anonymous> (https://www.keeptrack.space/app/js/main.d2d0055a530f0fc4e587.js:64:23915)

**Comment by thkruz** [comment]
Looks like a race condition. Added better error checking.
