### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by dev-tvo** [thkruz/keeptrack.space#912]
#### User Description
Type what you were trying to do here...

#### Version
10.0.0 - August 15, 2024
#### Error Title
TypeError
#### Error Message
a.isStatic is not a function
#### Stack
TypeError: a.isStatic is not a function
    at we.updateOrbitBuffer (https://www.keeptrack.space/app/js/main.50ad1b674ed2a40db58f.js:1253:10049)
    at Object.k [as cb] (https://www.keeptrack.space/app/js/303.793f6197a405b23e5516.js:205:165)
    at https://www.keeptrack.space/app/js/main.50ad1b674ed2a40db58f.js:2:1682959
    at Array.forEach (<anonymous>)
    at Object.runEvent (https://www.keeptrack.space/app/js/main.50ad1b674ed2a40db58f.js:2:1682945)
    at bt.update (https://www.keeptrack.space/app/js/main.50ad1b674ed2a40db58f.js:1715:114450)
    at Pt.update_ (https://www.keeptrack.space/app/js/main.50ad1b674ed2a40db58f.js:1754:6143)
    at Pt.gameLoop (https://www.keeptrack.space/app/js/main.50ad1b674ed2a40db58f.js:1715:117546)

**Comment by thkruz** [comment]
This is likely related to the old missile simulation files. I am working on a fix now to convert them from the legacy format into the new MissileObject classes which have the isStatic method.

**Comment by thkruz** [comment]
Fixed in 58ff44ab4993d5cb89b916b8ed68eb4909f8630a
