### ISSUE TITLE
TypeError in tleManagerInstance.loadCatalog

### ISSUE THREAD

**Issue by maeldd** [thkruz/keeptrack.space#961]
#### User Description
Type what you were trying to do here...

#### Version
10.2.0 - October 1, 2024
#### Error Title
TypeError
#### Error Message
Failed to fetch
#### Stack
TypeError: Failed to fetch
    at d.<anonymous> (https://app.keeptrack.space/js/main.844f662481b3155aa206.js:1048:32302)
    at Generator.next (<anonymous>)
    at https://app.keeptrack.space/js/main.844f662481b3155aa206.js:1048:31101
    at new Promise (<anonymous>)
    at c (https://app.keeptrack.space/js/main.844f662481b3155aa206.js:1048:30846)
    at d.load (https://app.keeptrack.space/js/main.844f662481b3155aa206.js:1048:31725)
    at Mn.<anonymous> (https://app.keeptrack.space/js/main.844f662481b3155aa206.js:1901:4695)
    at Generator.next (<anonymous>)
    at r (https://app.keeptrack.space/js/main.844f662481b3155aa206.js:1863:115424)

**Comment by thkruz** [comment]
Something prevented you from getting the catalog (https://storage.keeptrack.space/data/tle.json). I saw that the VPS that serves that file crashed during the huge influx of traffic from Hacker News. I think this was an infrastructure failure not a code issue.
