### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by haardsoni** [thkruz/keeptrack.space#963]
#### User Description
Type what you were trying to do here...

#### Version
10.0.1 - August 17, 2024
#### Error Title
TypeError
#### Error Message
Cannot read properties of undefined (reading 'track')
#### Stack
TypeError: Cannot read properties of undefined (reading 'track')
    at g.selectSatObject_ (https://thkruz.github.io/keeptrack.space/js/main.f9be98443a34b45da755.js:481:7313)
    at g.selectSat (https://thkruz.github.io/keeptrack.space/js/main.f9be98443a34b45da755.js:481:4440)
    at Ae.canvasMouseUp (https://thkruz.github.io/keeptrack.space/js/main.f9be98443a34b45da755.js:1389:398341)
    at HTMLCanvasElement.<anonymous> (https://thkruz.github.io/keeptrack.space/js/main.f9be98443a34b45da755.js:1389:400394)

**Comment by haardsoni** [comment]
Small request: Optimization.

I had frequently observed overheating and lag using the live website. The experience is not smooth mainly due to the heavy graphics rendering and the number of satellites.

**Comment by thkruz** [comment]
Definitely more that can be done on the mobile side. What kind of device are you using? I test against a Pixel 7. If you are in a lower end device I can take a look at trying to determine that programmatically and then disable more of the scene objects.

**Comment by haardsoni** [comment]
I am currently using the base variant of MacBook Air M1 2020 with 8GB RAM. On the mobile side, I am not eligible to say since I haven't tried it yet.
