### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by ssm0901** [thkruz/keeptrack.space#964]
#### User Description
Type what you were trying to do here...

#### Version
10.2.0 - October 1, 2024
#### Error Title
TypeError
#### Error Message
Cannot read properties of undefined (reading 'value')
#### Stack
TypeError: Cannot read properties of undefined (reading 'value')
    at oi.updateZoom_ (https://app.keeptrack.space/js/856.75b825ad522544ece5db.js:797:10563)
    at oi.updateGamepad (https://app.keeptrack.space/js/856.75b825ad522544ece5db.js:797:7854)
    at https://app.keeptrack.space/js/main.844f662481b3155aa206.js:2:1388099
    at Array.forEach (<anonymous>)
    at Object.runEvent (https://app.keeptrack.space/js/main.844f662481b3155aa206.js:2:1388085)
    at xn.update (https://app.keeptrack.space/js/main.844f662481b3155aa206.js:1863:114330)
    at Mn.update_ (https://app.keeptrack.space/js/main.844f662481b3155aa206.js:1901:6122)
    at Mn.gameLoop (https://app.keeptrack.space/js/main.844f662481b3155aa206.js:1863:117540)

**Comment by thkruz** [comment]
Can you tell me what kind of controller you were using?

I mapped everything to an Xbox controller because I had one handy and it was mainly for demonstration purposes. The error is caused by trying to access buttons 7 and 8 on whatever controller you had plugged in, which were evidently not there.
