### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by lch743** [thkruz/keeptrack.space#980]
#### User Description
Type what you were trying to do here...

#### Version
10.0.1 - August 17, 2024
#### Error Title
TypeError
#### Error Message
Cannot read properties of undefined (reading 'track')
#### Stack
TypeError: Cannot read properties of undefined (reading 'track')
    at Object.cb (https://thkruz.github.io/keeptrack.space/js/main.f9be98443a34b45da755.js:45:3960)
    at https://thkruz.github.io/keeptrack.space/js/main.f9be98443a34b45da755.js:2:1684035
    at Array.forEach (<anonymous>)
    at Object.runEvent (https://thkruz.github.io/keeptrack.space/js/main.f9be98443a34b45da755.js:2:1684021)
    at pt.bottomIconPress (https://thkruz.github.io/keeptrack.space/js/main.f9be98443a34b45da755.js:1810:23430)
    at HTMLDivElement.<anonymous> (https://thkruz.github.io/keeptrack.space/js/main.f9be98443a34b45da755.js:1810:23732)

**Comment by thkruz** [comment]
Looks like something caused the analytics tool to fail. Probably some kind of ad/cookie blocker. The tool was meant to be ignored if it is blocked. I updated the code to handle that better.
