### ISSUE TITLE
Error in Global Error Trapper

### ISSUE THREAD

**Issue by Patdwl** [thkruz/keeptrack.space#987]
#### User Description
Type what you were trying to do here...

#### Version
10.2.2 - October 30, 2024
#### Error Title
Error
#### Error Message
color buffer for 16579631 not valid
#### Stack
Error: color buffer for 16579631 not valid
    at Ee.checkColorBufferValidity_ (https://app.keeptrack.space/js/main.35cf69fe385caf4e7b4e.js:1477:12272)
    at Ee.checColorBuffersValidity_ (https://app.keeptrack.space/js/main.35cf69fe385caf4e7b4e.js:1477:12072)
    at Ee.drawHoverObjectOrbit_ (https://app.keeptrack.space/js/main.35cf69fe385caf4e7b4e.js:1477:11877)
    at Ee.draw (https://app.keeptrack.space/js/main.35cf69fe385caf4e7b4e.js:1477:6342)
    at hn.renderOpaque (https://app.keeptrack.space/js/main.35cf69fe385caf4e7b4e.js:1853:5179)
    at hn.render (https://app.keeptrack.space/js/main.35cf69fe385caf4e7b4e.js:1853:3027)
    at Ln.render (https://app.keeptrack.space/js/main.35cf69fe385caf4e7b4e.js:1939:104958)
    at Mn.draw_ (https://app.keeptrack.space/js/main.35cf69fe385caf4e7b4e.js:1977:3269)
    at Mn.gameLoop (https://app.keeptrack.space/js/main.35cf69fe385caf4e7b4e.js:1939:117556)

**Comment by thkruz** [comment]
Defensive code added to avoid this issue in https://github.com/thkruz/keeptrack.space/commit/1f5c8da12d74a497379b3f9c0f22b0b1dbf64374
