### ISSUE TITLE
InvalidStateError in Global Error Trapper

### ISSUE THREAD

**Issue by heunzb** [thkruz/keeptrack.space#988]
#### User Description
Type what you were trying to do here...

#### Version
10.2.2 - October 30, 2024
#### Error Title
InvalidStateError
#### Error Message
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
#### Stack
InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at S.drawEarthLayer_ (http://192.168.1.103:8080/js/main.35cf69fe385caf4e7b4e.js:1006:5437)
    at S.resize2DMap_ (http://192.168.1.103:8080/js/main.35cf69fe385caf4e7b4e.js:1006:5343)
    at http://192.168.1.103:8080/js/main.35cf69fe385caf4e7b4e.js:1006:299

**Comment by thkruz** [comment]
WebGL was unable to load the earth image. I would need more info to troubleshoot. Initial thoughts:

Were you on an lower-end/older mobile device or tablet?
Were you on an apple product and/or using Safari? 

I am going to mark it as closed for now since it appears to be an issue with your environment not the code.
