### ISSUE TITLE
Error in breakup.ts

### ISSUE THREAD

**Issue by zhaohangli** [thkruz/keeptrack.space#992]
#### User Description
Type what you were trying to do here...

#### Version
10.2.2 - December 12, 2024
#### Error Title
Error
#### Error Message
Failed to find solution with Nbound direction
#### Stack
Error: Failed to find solution with Nbound direction
    at ht.onSubmit_ (https://app.keeptrack.space/js/165.646cfaa24316541e5498.js:566:1802)
    at https://app.keeptrack.space/js/165.646cfaa24316541e5498.js:566:231
    at https://app.keeptrack.space/js/main.7cac9624e753a1550358.js:2:1397789

**Comment by thkruz** [comment]
Math failed trying to create a breakup. 

I will put in a catch to provide a lot more simulation data if this happens again. Hard to troubleshoot it without knowing your time/date and the TLE you were running the breakup script on.

Thanks for reporting this.

**Comment by thkruz** [comment]
Appears to have been fixed already and I forgot to update github.
