### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by githubchina001** [thkruz/keeptrack.space#993]
#### User Description
Type what you were trying to do here...

#### Version
10.2.2 - December 12, 2024
#### Error Title
TypeError
#### Error Message
e.rae is not a function
#### Stack
TypeError: e.rae is not a function
    at Dn.rae (https://app.keeptrack.space/js/main.7cac9624e753a1550358.js:1428:237903)
    at Dn.isSatInFov (https://app.keeptrack.space/js/main.7cac9624e753a1550358.js:1428:301989)
    at Ci.generatePlotData_ (https://app.keeptrack.space/js/165.646cfaa24316541e5498.js:890:2106)
    at Ci.updatePlot_ (https://app.keeptrack.space/js/165.646cfaa24316541e5498.js:890:1439)
    at push.70906.constructor.bottomIconCallback (https://app.keeptrack.space/js/165.646cfaa24316541e5498.js:882:4584)
    at Object.cb (https://app.keeptrack.space/js/main.7cac9624e753a1550358.js:45:4568)
    at https://app.keeptrack.space/js/main.7cac9624e753a1550358.js:2:1388099
    at Array.forEach (<anonymous>)
    at Object.runEvent (https://app.keeptrack.space/js/main.7cac9624e753a1550358.js:2:1388085)
    at onReady.bottomIconPress (https://app.keeptrack.space/js/main.7cac9624e753a1550358.js:1853:18884)

**Comment by thkruz** [comment]
It looks like a lack of validation in the callback when you close a plot menu. I should be able to add a validation check prior to running the callback.

**Comment by thkruz** [comment]
Trap added for this error. Will be in the next build.
